// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xozwemvvmahezoadqnis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvendlbXZ2bWFoZXpvYWRxbmlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzYyMjAsImV4cCI6MjA2NTU1MjIyMH0.5DecyJyH3Ox3IPoFkXXn4lkq3i1PtW_pMDFujEqoPsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);